# Generated by Django 6.0.4 on 2026-05-01 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Ej: PS5, XBX, NS', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideojuegoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lanzamiento', models.DateField()),
                ('version', models.CharField(blank=True, max_length=50)),
                ('exclusivo', models.BooleanField(default=False)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuegos.plataforma')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuegos.videojuego')),
            ],
        ),
        migrations.AddField(
            model_name='videojuego',
            name='plataformas',
            field=models.ManyToManyField(through='videojuegos.VideojuegoPlataforma', to='videojuegos.plataforma'),
        ),
        migrations.AddConstraint(
            model_name='videojuegoplataforma',
            constraint=models.UniqueConstraint(fields=('videojuego', 'plataforma'), name='unique_videojuego_plataforma'),
        ),
    ]
