# Generated by Django 6.0.4 on 2026-05-24 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_alter_plataforma_codigo_biblioteca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegoplataforma',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='videojuegos.plataforma'),
        ),
        migrations.AddIndex(
            model_name='biblioteca',
            index=models.Index(fields=['usuario'], name='videojuegos_usuario_8e2e9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='biblioteca',
            constraint=models.UniqueConstraint(fields=('usuario', 'videojuego'), name='unique_usuario_videojuego'),
        ),
    ]
