# Generated by Django 6.0.4 on 2026-05-31 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0003_alter_videojuegoplataforma_plataforma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='biblioteca',
            name='videojuegos_usuario_8e2e9b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='biblioteca',
            name='unique_usuario_videojuego',
        ),
        migrations.RemoveConstraint(
            model_name='videojuegoplataforma',
            name='unique_videojuego_plataforma',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='plataformas',
        ),
        migrations.RenameField(
            model_name='videojuego',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='plataforma',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_lanzamiento',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='precio',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='anio_lanzamiento',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plataforma',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='bibliotecausuario',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to='videojuegos.plataforma'),
        ),
        migrations.AddField(
            model_name='bibliotecausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bibliotecausuario',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='videojuegos.videojuego'),
        ),
        migrations.RemoveField(
            model_name='videojuegoplataforma',
            name='plataforma',
        ),
        migrations.RemoveField(
            model_name='videojuegoplataforma',
            name='videojuego',
        ),
        migrations.AlterUniqueTogether(
            name='bibliotecausuario',
            unique_together={('usuario', 'videojuego', 'plataforma')},
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
        migrations.DeleteModel(
            name='VideojuegoPlataforma',
        ),
    ]
