# Generated by Django 6.0.4 on 2026-05-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0004_bibliotecausuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='anio_lanzamiento',
            field=models.DateField(),
        ),
    ]
