# Generated by Django 6.0.4 on 2026-05-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0005_alter_videojuego_anio_lanzamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='coverUrl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
