# Generated by Django 6.0.4 on 2026-05-31 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0006_videojuego_coverurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideojuegoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('jugando', 'Jugando'), ('completado', 'Completado'), ('abandonado', 'Abandonado')], max_length=20)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuegos.plataforma')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videojuegos.videojuego')),
            ],
            options={
                'unique_together': {('videojuego', 'plataforma')},
            },
        ),
    ]
