# Generated by Django 6.0.4 on 2026-05-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0007_videojuegoplataforma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideojuegoPlataforma',
        ),
    ]
