# Generated by Django 6.0.4 on 2026-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0008_delete_videojuegoplataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='videojuego',
            name='generos',
            field=models.ManyToManyField(to='videojuegos.genero'),
        ),
    ]
