# Generated by Django 5.2.11 on 2026-02-08 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Género',
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('fecha_estreno', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Película',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.genero')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.pelicula')),
            ],
            options={
                'verbose_name': 'Género de película',
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(through='cine.PeliculaGenero', to='cine.genero'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(max_length=100)),
                ('idioma', models.CharField(max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='cine.usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
            },
        ),
        migrations.CreateModel(
            name='Visualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visualizacion', models.DateField()),
                ('minutos_vistos', models.IntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.usuario')),
            ],
            options={
                'verbose_name': 'Visualización',
            },
        ),
        migrations.AddConstraint(
            model_name='peliculagenero',
            constraint=models.UniqueConstraint(fields=('pelicula', 'genero'), name='unique_pelicula_genero'),
        ),
    ]
